modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Quicksaving"
logoFile="icon.png"

[[mods]]
modId="quicksaving"
version="1.2"
displayName="Quicksaving"
displayURL="https://serilum.com/mod/quicksaving"
authors="Rick South"
description='''Adds quicksave and quickload capabilities, optionally client-side only.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.quicksaving]]
    modId="collective"
    mandatory=true
    versionRange="[7.78,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quicksaving]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"
