modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Quicksaving"
logoFile="icon.png"

[[mods]]
modId="quicksaving"
version="2.0"
displayName="Quicksaving"
displayURL="https://serilum.com/mod/quicksaving"
authors="Serilum"
description='''Adds quicksave and quickload capabilities, optionally client-side only.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.quicksaving]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.quicksaving]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "quicksaving.mixins.json"